title: Sthymuli
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://tomblackroad.github.io/sthymuli.web/

aux_links:
  B&M project: https://belearn.swiss/en/projekt/the-beauty-and-the-machine-joining-aesthetics-and-robotics-in-education/
